import settings from '../../../config/webSettings';
import firebase from 'firebase';
console.log(settings.firebase);
export const firebaseApp = firebase.initializeApp(settings.firebase);

export const ref = firebase.database().ref();
export const fb = firebase;
export const firebaseAuth = firebaseApp.auth();
export const googleProvider = new firebase.auth.GoogleAuthProvider();
export const facebookProvider = new firebase.auth.FacebookAuthProvider();
export const anonymousAuthenticate = () => firebaseApp.auth().signInAnonymously();
export const googleAuthenticate = () => firebaseApp.auth().signInWithPopup(googleProvider);
export const googleAuthenticateRedirect = () => firebaseApp.auth().signInWithRedirect(googleProvider);
export const facebookAuthenticateRedirect = () => firebaseApp.auth().signInWithRedirect(facebookProvider);
export const facebookAuthenticate = () => firebaseApp.auth().signInWithPopup(facebookProvider);
export const currentUser = () => firebaseApp.auth().currentUser;
export const fetchProvidersForEmail = (email) => firebaseApp.auth().fetchProvidersForEmail(email);
export const getRedirectResult = () => firebaseApp.auth().getRedirectResult();
export const googleLinkWithRedirect = () => firebaseApp.auth().currentUser.linkWithRedirect(googleProvider);
export const facebookLinkWithRedirect = () => firebaseApp.auth().currentUser.linkWithRedirect(facebookProvider);
